### ISSUE TITLE
timezone-series-0.1.5.1 does not compile with GHC 8.0.1

### ISSUE THREAD

**Issue by peti** [ygale/timezone-series#2]
I'm getting the following build errors:

```
Building timezone-series-0.1.5.1...
Preprocessing library timezone-series-0.1.5.1...
[1 of 1] Compiling Data.Time.LocalTime.TimeZone.Series ( Data/Time/LocalTime/TimeZone/Series.hs, dist/build/Data/Time/LocalTime/TimeZone/Series.o )

Data/Time/LocalTime/TimeZone/Series.hs:80:22: error:
    • Couldn't match type ‘TimeZoneSeries’ with ‘Maybe TimeZoneSeries’
      Expected type: [(Char, String)] -> Maybe TimeZoneSeries
        Actual type: [(Char, String)] -> TimeZoneSeries
    • In the expression: flip TimeZoneSeries [] . buildTime locale
      In an equation for ‘buildTime’:
          buildTime locale = flip TimeZoneSeries [] . buildTime locale
      In the instance declaration for ‘ParseTime TimeZoneSeries’

Data/Time/LocalTime/TimeZone/Series.hs:80:47: error:
    • Couldn't match type ‘Maybe t1’ with ‘TimeZone’
      Expected type: [(Char, String)] -> TimeZone
        Actual type: [(Char, String)] -> Maybe t1
    • In the second argument of ‘(.)’, namely ‘buildTime locale’
      In the expression: flip TimeZoneSeries [] . buildTime locale
      In an equation for ‘buildTime’:
          buildTime locale = flip TimeZoneSeries [] . buildTime locale

Data/Time/LocalTime/TimeZone/Series.hs:170:22: error:
    • Couldn't match type ‘ZoneSeriesTime’ with ‘Maybe ZoneSeriesTime’
      Expected type: [(Char, String)] -> Maybe ZoneSeriesTime
        Actual type: [(Char, String)] -> ZoneSeriesTime
    • In the expression: zonedTimeToZoneSeriesTime . buildTime locale
      In an equation for ‘buildTime’:
          buildTime locale = zonedTimeToZoneSeriesTime . buildTime locale
      In the instance declaration for ‘ParseTime ZoneSeriesTime’

Data/Time/LocalTime/TimeZone/Series.hs:170:50: error:
    • Couldn't match type ‘Maybe t0’ with ‘ZonedTime’
      Expected type: [(Char, String)] -> ZonedTime
        Actual type: [(Char, String)] -> Maybe t0
    • In the second argument of ‘(.)’, namely ‘buildTime locale’
      In the expression: zonedTimeToZoneSeriesTime . buildTime locale
      In an equation for ‘buildTime’:
          buildTime locale = zonedTimeToZoneSeriesTime . buildTime locale
```

**Comment by ryantrinkle** [comment]
@peti I believe #1 addresses this

**Comment by ygale** [comment]
PRs #1, #3, and #4 all address this. I pushed a change that does the same thing, but using a cabal flag instead of CPP. I verified that it works with both pre-1.6 and post-1.6 time library. But I currently can only test using GHC 7.8. If someone could test with GHC 8 and/or GHC 7.10 and report back, I would be grateful. Thanks!

**Comment by peti** [comment]
Why don't you let travis-ci do the testing? Check out https://github.com/hvr/multi-ghc-travis/.

Edit: Sorry, didn't intent to close this.

**Comment by ygale** [comment]
@peti Yes that would be great. In fact - I was the one who set up travis for the Haskell Platform a few years ago. But I don't see myself having time to set that up here very soon.

In fact - if rather than just testing this, someone would like to send a PR to set up travis, that would be wonderful!

**Comment by peti** [comment]
Version 1.6 is broken when compiling with GHC 8.x:

```
/tmp/timezone-series-0.1.6$ cabal build
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring timezone-series-0.1.6...
Warning: 'hs-source-dirs: time_post_1_6' directory does not exist.
Building timezone-series-0.1.6...
Preprocessing library timezone-series-0.1.6...
cabal: can't find source for
Data/Time/LocalTime/TimeZone/Internal/MapBuiltTime in ., time_post_1_6,
dist/build/autogen
```

**Comment by ygale** [comment]
Thanks! This is due to a bug in `cabal sdist`, haskell/cabal#367. It was fixed in cabal-1.24, but I was using cabal-1.22. I uploaded timezone-series-0.1.6.1 and deprecated timezone-series-0.1.6.

**Comment by peti** [comment]
OK. The new version compiles fine. Thanks!

P. S.: I hope you noticed https://github.com/ygale/timezone-series/pull/5?
